### ISSUE TITLE
dep: nethermind returns custom errors in manner not expected by ethers

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/tenderly-watch-tower#11]
**Problem**

Gnosis Chain is often used as a testing ground for low value-at-risk trades in a "testing" environment. However, Gnosis Chain is heavily biased towards Nethermind as an execution client, and as such, inherits bugs there. Notably, https://github.com/NethermindEth/nethermind/issues/6024 refers to Nethermind not correctly returning revert codes (as may be expected).

**Solution**

There are two options:

1. Investigate use of `eth_estimateGas` to see if this would return the correct `revert` value.
2. Derive some intermediate step for handling of Gnosis Chain until nodes are migrated to a version of Nethermind that fixes this fundamental issue.

**CC**: @cowprotocol/backend @cowprotocol/frontend

**Comment by anxolin** [comment]
Yes, this is why some PR in the past was pre-checking the `auth`

Good to investigate in this issue, but if the conclusion is that we should not rely on RPC implementations to know about the reversion cause, I would prefer to verify the state of the blockchain and not to do a CALL and check the error that is raised. The state will be standard across different RPC providers, so this will be more resilient.

If the errors should be part of the RPC node standards, and is just a bug that Nethermind will fix, then I agree we should use them.

**Comment by mfw78** [comment]
Investigating this issue further in the hunt for zero errors, it turns out that the Nethermind RPC does actually return the reversion data, but not in a format that is expected by `ethers` when deserializing the `JSON-RPC` response. Logs below from a playground:

**Nethermind Gnosis Chain RPC** 

```raw
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74","data":"0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32015,\"message\":\"VM execution error.\",\"data\":\"Reverted 0x7a933234\"},\"id\":44}","error":{"code":-32015,"data":"Reverted 0x7a933234"},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xfdafc9d1902f4e0b84f65f49f244b32b31013b74\",\"data\":\"0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://api-url/eth"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:66:16)
    at JsonRpcProvider.<anonymous> (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at step (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    to: '0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74',
    data: '0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    accessList: null
  },
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32015,\"message\":\"VM execution error.\",\"data\":\"Reverted 0x7a933234\"},\"id\":44}", error={"code":-32015,"data":"Reverted 0x7a933234"}, requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xfdafc9d1902f4e0b84f65f49f244b32b31013b74\",\"data\":\"0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://api-url/eth", code=SERVER_ERROR, version=web/5.7.1)
      at Logger.makeError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at /home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/src.ts/index.ts:341:28
      at step (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x7a933234"},"id":44}',
    error: Error: VM execution error.
        at getResult (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
        at processJsonFunc (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/src.ts/index.ts:383:22)
        at /home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/src.ts/index.ts:320:42
        at step (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: -32015,
      data: 'Reverted 0x7a933234'
    },
    requestBody: '{"method":"eth_call","params":[{"to":"0xfdafc9d1902f4e0b84f65f49f244b32b31013b74","data":"0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"},"latest"],"id":44,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://api-url/eth'
  }
}
```

**Alchemy Mainnet RPC**

```raw
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getTradeableOrderWithSignature(address,(address,bytes32,bytes),bytes,bytes32[])", data="0x7a933234", errorArgs=[], errorName="SingleOrderNotAuthed", errorSignature="SingleOrderNotAuthed()", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.decodeFunctionResult (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getTradeableOrderWithSignature(address,(address,bytes32,bytes),bytes,bytes32[])',
  data: '0x7a933234',
  errorArgs: [],
  errorName: 'SingleOrderNotAuthed',
  errorSignature: 'SingleOrderNotAuthed()',
  address: '0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74',
  args: [
    '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    {
      handler: '0x6cF1e9cA41f7611dEf408122793c358a3d11E5a5',
      salt: '0xd116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f7',
      staticInput: '0xd116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f7'
    },
    '0x',
    []
  ],
  transaction: {
    data: '0x26e0a1960000000000000000000000005fbdb2315678afecb367f032d93f642f64180aa30000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000001400000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a5d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020d116a28addff79282ce9b2e5dc78b8d11ae585440fb66bf263e3a328c9d2a1f700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    to: '0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74'
  }
}
```

As the watch tower's polling is relying on the `error.errorName` in order to indicate what the reversion condition is, this functionality doesn't work correctly on Gnosis Chain (or Nethermind RPCs). 

However, we can access the reverted message at `error.error.error.data` (yes, it's quite nested). This will yield something like: `Reverted 0x7a933234`.

The existing switch statement in the watch tower is only concerned with `OrderNotValid`, `SingleOrderNotAuthed`, and `ProofNotAuthed`, so we can match the the reverted message against the selector, and do so only in the `default:` section of the `switch` statement.

This will:

1. Allow for minimal changes, working with the current version of Nethermind.
2. Provided Nethermind implement fixes to bring their JSON-RPC responses in line with `erigon` / `geth` etc, the watch tower will automatically work with a change to underlying RPC node software.

**Comment by fleupold** [comment]
Sorry, I'm late to this party but awesome debugging! I think manually making and parsing the RPC request may be a good option (unless we can upstream the fix to ethers, but this will likely take a long time to make it into production).

An alternative that crossed my mind is that we could spawn a transaction simulator a la https://github.com/EnsoFinance/transaction-simulator internally, which may also give us proper revert reasons.

**Comment by mfw78** [comment]
Additional testing when implementing #15 revealed that even for non-Nethermind nodes, *parameterised* custom errors aren't supported properly in `ethers`. Example logs:

```raw
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getTradeableOrderWithSignature(address,(address,bytes32,bytes),bytes,bytes32[])", data="0xc8fc272500000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011616674657220747761702066696e697368000000000000000000000000000000", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Interface.decodeFunctionResult (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/mfw78/src/ethers-playground/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getTradeableOrderWithSignature(address,(address,bytes32,bytes),bytes,bytes32[])',
  data: '0xc8fc272500000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011616674657220747761702066696e697368000000000000000000000000000000',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74',
  args: [
    '0x6Dc48b0f065B8967F0f2271d6aB153DCdA3269F6',
    {
      handler: '0x6cF1e9cA41f7611dEf408122793c358a3d11E5a5',
      salt: '0x00000000000000000000000000000000000000000000000000000018a0398081',
      staticInput: '0x00000000000000000000000072e4f9f808c49a2a61de9c5896298920dc4eeea9000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000006dc48b0f065b8967f0f2271d6ab153dcda3269f600000000000000000000000000000000000000000000000000000374c1a6700000000000000000000000000000000000000000000000000029a389012aef2f690000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000008700000000000000000000000000000000000000000000000000000000000000000c748f647179000fdeaff7a288564347d19ea26d0d451a943815ae4d3c0ac01c0'
    },
    '0x',
    []
  ],
  transaction: {
    data: '0x26e0a1960000000000000000000000006dc48b0f065b8967f0f2271d6ab153dcda3269f60000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002600000000000000000000000006cf1e9ca41f7611def408122793c358a3d11e5a500000000000000000000000000000000000000000000000000000018a03980810000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000014000000000000000000000000072e4f9f808c49a2a61de9c5896298920dc4eeea9000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000006dc48b0f065b8967f0f2271d6ab153dcda3269f600000000000000000000000000000000000000000000000000000374c1a6700000000000000000000000000000000000000000000000000029a389012aef2f690000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000008700000000000000000000000000000000000000000000000000000000000000000c748f647179000fdeaff7a288564347d19ea26d0d451a943815ae4d3c0ac01c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    to: '0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74'
  }
}
```

In this case, we can see that the order has revered with `OrderNotValid`, as the custom error is _actually_ `OrderNotValid(string)`, which corresponds to an error `bytes4` of `0xc8fc2725`. The following data corresponds to the error string, which quickly decoded through `chisel` yields `after twap finish` as below:

![image](https://github.com/cowprotocol/tenderly-watch-tower/assets/53399572/cf11c664-f386-4a9d-ad7a-7da86f8a6923)

Therefore, the fix has been adapted to support this case of raw custom error decoding in the event of a parameterised error.
